run-dist: build lint run

build:
	gradle clean
	gradle build
	# ./gradlew clean
	# ./gradlew installDist

lint:
	gradle checkstyleMain

run:
	gradle run
	# ./build/install/app/bin/app


.PHONY: build
